services:
  - type: web
    name: ml-model-api
    env: python
    buildCommand: pip install -r requirements.txt && python model.py
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
